### ISSUE TITLE
Failing to capture colors inside gradient

### ISSUE THREAD

**Issue by PeterKnight** [rsanchez/css-color-extractor#3]
I've noticed this script sometimes fails to capture colours. Here's a gradient example (generated on cssgradient.io):

`colorExtractor.fromString('linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%');
// returns []`

**Comment by rsanchez** [comment]
That string is missing a close parens so it's not valid CSS. Also fromString expects a full css rule (selector + curly brackets + declarations), so this works:

```
colorExtractor.fromString('a { background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%) }'); // returns ['rgba(2,0,36,1)', 'rgba(9,9,121,1)', 'rgba(0,212,255,1)']
```
